import Head from "next/head";
import SignIn from "./components/SignIn";
import User from "./components/User";

function page() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <SignIn />
        {/* @ts-expect-error server component */}
        <User />
      </main>
    </>
  );
}

export default page;
